name: example
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/NicolaVerbeeck/flutter_secure_file_storage_inspector
repository: https://github.com/NicolaVerbeeck/flutter_secure_file_storage_inspector
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_file_storage: ^0.0.4
  storage_inspector: ^0.1.2
  flutter_secure_storage: ^5.0.2
  flutter_secure_file_storage_inspector:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
